services:
  - type: web
    name: potato-api
    rootDir: api
    runtime: python
    envVars:
      - key: PYTHON-VERSION
        value: "3.10.20"
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free

  - type: web
    name: potato-disease-classifier
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://potato-api.onrender.com